### PR TITLE
add: lint for broad and bare exception handlers

### PR DESCRIPTION
**Pull request by chdsbd**

### CODE REVIEW

**Review by sbdchd — APPROVED** [review]

**Comment by bz2** [comment]
This lint is a bad idea unless it handles the common case of an except clause with a reraise. See https://github.com/PyCQA/pycodestyle/issues/703 for details.

**Comment by chdsbd** [comment]
@bz2 Good catch. I'll make a fix.

**Comment by chdsbd** [comment]
@bz2 Fixed in 0.6.1 via #35.

**Comment by bz2** [comment]
Amazing, thanks @chdsbd!

**Pull request merged**
